#after_success:
#  - semantic-release --prepare @conveyal/maven-semantic-release --publish @semantic-release/github,@conveyal/maven-semantic-release --verify-conditions @semantic-release/github,@conveyal/maven-semantic-release --verify-release @conveyal/maven-semantic-release --skip-maven-deploy

  
before_install:
  - chmod 777 cd/before-deploy.sh
  - cd/before-deploy.sh
#  # only install signing keys under the same circumstances we do a mvn deploy later
#  if [[ "$TRAVIS_PULL_REQUEST" = false ]] && [[ "$TRAVIS_BRANCH" = master ]]; then
#    openssl aes-256-cbc -K $encrypted_319571283a54_key -iv $encrypted_319571283a54_iv -in maven-artifact-signing-key.asc.enc -out maven-artifact-signing-key.asc -d
#    gpg --import --batch maven-artifact-signing-key.asc
#  fi

#before_script:
#  - yarn global add https://github.com/conveyal/maven-semantic-release.git#e5551beb4ec266bb520ae5ff155bc0d04acf8f05 semantic-release@15



cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.yarn-cache'
    - '$HOME/.sonar/cache'
  
# See https://github.com/SonarSource/sq-com_example_java-maven-travis/blob/master/.travis.yml,
# a lot of what you see here borrowed from there. I got that URL from
# this page:
# https://docs.travis-ci.com/user/sonarcloud/
language: java

install: true

jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13

matrix:
  allow_failures:
    jdk:
      - openjdk12
      - openjdk13

stages:
  - test
  - report
  - deploy


addons:
  sonarcloud:
    organization: "joquijada-github"



# Need to define the `test` stage here, else nothing runs in Travis CI.
# Maybe my understanding of things is wrong, but I thought the `test`
# stage is the default and always runs, hence no need to explicitly define 
# anywhere. Oh well at least I got it to work.
jobs:
  include:
    - stage: test
      # This stage runs for all branches
      name: Test the Code
      script: mvn clean package -P coverage
      if: type IN (push, pull_request)
    - stage: report
      # Report only on the master branch
      name: Report Code Quality
      script: mvn sonar:sonar
      if: branch = master
    - stage: deploy
      # This stage runs for all branches
      name: Deploy to Maven Repo
      script:
        #- cd/before-deploy.sh
        - yarn global add https://github.com/conveyal/maven-semantic-release.git#e5551beb4ec266bb520ae5ff155bc0d04acf8f05 semantic-release@15
        # If we're deploying, it means all tests passed prior to pull request getting landed, hence skip running tests again
        - mvn package -Dmaven.test.skip=true
        - semantic-release --prepare @conveyal/maven-semantic-release --publish @semantic-release/github,@conveyal/maven-semantic-release --verify-conditions @semantic-release/github,@conveyal/maven-semantic-release --verify-release @conveyal/maven-semantic-release --skip-maven-deploy
      if: branch = master

