# See https://github.com/SonarSource/sq-com_example_java-maven-travis/blob/master/.travis.yml,
# a lot of what you see here borrowed from there. I got that URL from
# this page:
# https://docs.travis-ci.com/user/sonarcloud/ 
language: java

addons:
  sonarcloud:
    organization: "joquijada-github"


script:
  - mvn clean install -Pcoverage


cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'


jobs:
  include:
    - stage: report
      name: Report Code Quality
      script: mvn sonar:sonar
