# See https://github.com/SonarSource/sq-com_example_java-maven-travis/blob/master/.travis.yml,
# a lot of what you see here borrowed from there. I got that URL from
# this page:
# https://docs.travis-ci.com/user/sonarcloud/ 
language: java

addons:
  sonarcloud:
    organization: "joquijada-github"
    #token:
    #  secure: "*********" # encrypted value of your token


script:
  - mvn clean install sonar:sonar -Pcoverage


cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
