# See https://github.com/SonarSource/sq-com_example_java-maven-travis/blob/master/.travis.yml,
# a lot of what you see here borrowed from there. I got that URL from
# this page:
# https://docs.travis-ci.com/user/sonarcloud/ 
language: java

stages:
  - test
  - report


addons:
  sonarcloud:
    organization: "joquijada-github"


script:
  - mvn clean install -P coverage


cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'



# Need to define the `test` stage here, else nothing runs in Travis CI
# Maybe my understanding of things is wrong, but I thought the `test`
# stage is the default and always runs.
jobs:
  include:
      #- stage: test
      #name: Test the Code
      #script: mvn clean install -P coverage
    - stage: report
      name: Report Code Quality
      script: mvn sonar:sonar
      #if: branch = master
